modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/ModernGamingWorlds-Mods/Wooden-Utilities/issues"

[[mods]]
modId="woodenutilities"
version="${file.jarVersion}"
displayName="Wooden Utilities"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wooden-utilities"
credits="NovaMachina, LazyMinded, and many others"
authors="ModernGamingWorld, NovaMachina, LazyMinded"
description='''An all-new Minecraft Mod that adds more Wood-Related items to your daily Minecraft Experience.'''

[[dependencies.woodenutilities]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.woodenutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1, 1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.woodenutilities]]
   modId="libx"
   mandatory=true
   versionRange="[1.18.1-3.1.0,)"
   ordering="NONE"
   side="BOTH"
